name: Wiki Update Demo
run-name: Pushing Updates to BTA Wiki
on:
    push:
      branches:
        - wiki
jobs:
    post-to-wiki:
        name: Post Updates to Wiki
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
              with:
                repository: 'bloodydoves/BattleTech-Advanced'
                path: bta
            - name: Check out generation code
              uses: actions/checkout@v4
              with:
                repository: 'amidatelion/wiki-gen-poc'
                path: wiki-gen-poc
                ref: 'parser'
            - name: Run Generation Code
              env:
                WIKI_PASS: ${{ secrets.WIKI_PASS }}
                WIKI_USER: ${{ vars.WIKI_USER}}
              run: |
                python3 /home/runner/work/wiki-actions-poc/wiki-actions-poc/wiki-gen-poc/src/factionRenderer.py